
title: Lee's Time
email: lh.man@aol.com
description: >- # this means to ignore newlines until "baseurl:"
  What I need to be doing now!
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  leehman

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
#markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
